# pyrefly: ignore [missing-import]
from fastapi import FastAPI, HTTPException
# pyrefly: ignore [missing-import]
from fastapi.middleware.cors import CORSMiddleware
import os
import json

app = FastAPI(title="Groww Review Pulse API")

# Allow CORS for the Vite frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "data")

@app.get("/api/runs")
def get_runs():
    """
    Returns the history of all processed ISO weeks.
    """
    history_file = os.path.join(DATA_DIR, "run_history.json")
    if not os.path.exists(history_file):
        return {"runs": []}
    
    with open(history_file, "r") as f:
        data = json.load(f)
        
    return {"runs": data.get("runs", [])}

@app.get("/api/themes/{iso_week}")
def get_themes(iso_week: str):
    """
    Returns the generated themes, quotes, and action items for a specific week.
    """
    theme_file = os.path.join(DATA_DIR, f"themes_{iso_week}.json")
    if not os.path.exists(theme_file):
        raise HTTPException(status_code=404, detail="Theme data not found for this week. Was it generated by the pipeline?")
        
    with open(theme_file, "r") as f:
        data = json.load(f)
        
    return {"iso_week": iso_week, "themes": data}
