import re
from typing import List, Dict

def _standardize_text(text: str) -> str:
    """
    Standardizes text by lowercasing, stripping extra whitespace, and removing
    non-alphanumeric characters to allow robust matching.
    """
    if not text:
        return ""
    text = text.lower()
    # Remove all non-alphanumeric characters and collapse whitespace
    text = re.sub(r"[^a-z0-9\s]", "", text)
    return " ".join(text.split())

def validate_quote(quote: str, raw_reviews: List[Dict]) -> bool:
    """
    Validates if the generated quote verbatim matches a substring of at least
    one of the raw reviews.
    
    Args:
        quote: The candidate quote generated by the LLM.
        raw_reviews: List of review dictionaries containing the "text" key.
        
    Returns:
        bool: True if the quote matches a raw review, False otherwise.
    """
    if not quote or not raw_reviews:
        return False
        
    std_quote = _standardize_text(quote)
    
    # We require a minimum length of standard quote to avoid trivial short word matches (e.g. "good app")
    if len(std_quote.split()) < 3:
        return False
        
    for review in raw_reviews:
        review_text = review.get("text", "")
        std_review = _standardize_text(review_text)
        if std_quote in std_review:
            return True
            
    return False
